# Generated by Django 3.1 on 2020-08-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='whiskey_clubs',
            new_name='whiskey_club',
        ),
    ]
