# Generated by Django 3.1 on 2020-08-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whiskey_club',
            name='price',
        ),
    ]
