# Generated by Django 3.1 on 2020-08-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20200809_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whiskey_club',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
