# Generated by Django 3.1 on 2020-08-12 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20200809_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.subscription_type')),
                ('whiskey_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.whiskey_club')),
            ],
        ),
        migrations.AddField(
            model_name='subscription_type',
            name='whiskey_clubs',
            field=models.ManyToManyField(through='clubs.Subscriptions', to='clubs.Whiskey_club'),
        ),
    ]
