# Generated by Django 3.1 on 2020-08-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20200812_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AddField(
            model_name='subscription_type',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='subscription_type',
            name='whiskey_clubs',
            field=models.ManyToManyField(through='clubs.Subscriptions', to='clubs.Whiskey_club'),
        ),
    ]
