# Generated by Django 3.1 on 2020-08-14 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20200812_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_type',
            name='whiskey_clubs',
            field=models.ManyToManyField(related_name='whiskey_clubs', through='clubs.Subscriptions', to='clubs.Whiskey_club'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='Subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_subs', to='clubs.subscription_type'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='whiskey_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_subs', to='clubs.whiskey_club'),
        ),
    ]
