# Generated by Django 3.1 on 2020-08-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20200814_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_type',
            name='whiskey_clubs',
            field=models.ManyToManyField(related_name='whiskey_clubs', through='clubs.Subscriptions', to='clubs.Whiskey_club'),
        ),
    ]
